// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimeCRM_Api.Infraestructure.Persistence;

#nullable disable

namespace API_PRIMECRM.Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260916031821_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_PRIMECRM.Domain.Models.Inventario.InventoryMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductID");

                    b.ToTable("InventoryMovements");
                });

            modelBuilder.Entity("API_PRIMECRM.Domain.Models.Liquidaciones.Liquidation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LiquidationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SettlementReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SettlementTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Liquidations");
                });

            modelBuilder.Entity("API_PRIMECRM.Domain.Models.Liquidaciones.LiquidationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CashHandlingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DeliveryStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LiquidatedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LiquidationId")
                        .HasColumnType("int");

                    b.Property<decimal>("SaleAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tracking")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LiquidationId");

                    b.HasIndex("SaleId")
                        .IsUnique();

                    b.ToTable("LiquidationItems");
                });

            modelBuilder.Entity("API_PRIMECRM.Domain.Models.Masters.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("API_PRIMECRM.Domain.Models.Masters.CourierCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CashHandlingType")
                        .HasColumnType("int");

                    b.Property<decimal>("CashHandlingValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeliveryRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CourierCompanies");
                });

            modelBuilder.Entity("API_PRIMECRM.Domain.Models.Masters.ExpenseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ExpenseCategories");
                });

            modelBuilder.Entity("API_PRIMECRM.Domain.Models.Masters.FreightCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("OtherCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RatePerLB")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxPercentSV")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FreightCompanies");
                });

            modelBuilder.Entity("API_PRIMECRM.Domain.Models.Masters.IncomeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("IncomeCategories");
                });

            modelBuilder.Entity("API_PRIMECRM.Domain.Models.Masters.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BankName")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Last4")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("API_PRIMECRM.Domain.Models.Masters.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("API_PRIMECRM.Domain.Models.Masters.SalesChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SalesChannels");
                });

            modelBuilder.Entity("API_PRIMECRM.Domain.Models.Reabastecimimento.RestockOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ActualFreight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EstimatedFreight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EstimatedPounds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EstimatedTaxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FreightCompanyId")
                        .HasColumnType("int");

                    b.Property<decimal?>("LandedUnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OtherCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PackageStatus")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FreightCompanyId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("ProductId");

                    b.ToTable("RestockOrders");
                });

            modelBuilder.Entity("API_PRIMECRM.Domain.Models.Ventas.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CashHandlingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CourierCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FundsLocation")
                        .HasColumnType("int");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SaleAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SaleStatus")
                        .HasColumnType("int");

                    b.Property<int>("SalesChannelId")
                        .HasColumnType("int");

                    b.Property<int>("SettlementStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ShippingPaymentMode")
                        .HasColumnType("int");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("UnitCostAtSale")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CourierCompanyId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SalesChannelId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("API_PRIMECRM.Domain.Models.Inventario.InventoryMovement", b =>
                {
                    b.HasOne("API_PRIMECRM.Domain.Models.Masters.Product", "Product")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("API_PRIMECRM.Domain.Models.Liquidaciones.LiquidationItem", b =>
                {
                    b.HasOne("API_PRIMECRM.Domain.Models.Liquidaciones.Liquidation", "Liquidation")
                        .WithMany("Trackings")
                        .HasForeignKey("LiquidationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API_PRIMECRM.Domain.Models.Ventas.Sale", "Sale")
                        .WithOne("LiquidationItem")
                        .HasForeignKey("API_PRIMECRM.Domain.Models.Liquidaciones.LiquidationItem", "SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Liquidation");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("API_PRIMECRM.Domain.Models.Masters.Product", b =>
                {
                    b.HasOne("API_PRIMECRM.Domain.Models.Masters.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("API_PRIMECRM.Domain.Models.Reabastecimimento.RestockOrder", b =>
                {
                    b.HasOne("API_PRIMECRM.Domain.Models.Masters.FreightCompany", "FreightCompany")
                        .WithMany("RestockOrders")
                        .HasForeignKey("FreightCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API_PRIMECRM.Domain.Models.Masters.PaymentMethod", "PaymentMethod")
                        .WithMany("RestockOrders")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API_PRIMECRM.Domain.Models.Masters.Product", "Product")
                        .WithMany("RestockOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FreightCompany");

                    b.Navigation("PaymentMethod");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("API_PRIMECRM.Domain.Models.Ventas.Sale", b =>
                {
                    b.HasOne("API_PRIMECRM.Domain.Models.Masters.CourierCompany", "CourierCompany")
                        .WithMany("Sales")
                        .HasForeignKey("CourierCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API_PRIMECRM.Domain.Models.Masters.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API_PRIMECRM.Domain.Models.Masters.SalesChannel", "SalesChannel")
                        .WithMany("Sales")
                        .HasForeignKey("SalesChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourierCompany");

                    b.Navigation("Product");

                    b.Navigation("SalesChannel");
                });

            modelBuilder.Entity("API_PRIMECRM.Domain.Models.Liquidaciones.Liquidation", b =>
                {
                    b.Navigation("Trackings");
                });

            modelBuilder.Entity("API_PRIMECRM.Domain.Models.Masters.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("API_PRIMECRM.Domain.Models.Masters.CourierCompany", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("API_PRIMECRM.Domain.Models.Masters.FreightCompany", b =>
                {
                    b.Navigation("RestockOrders");
                });

            modelBuilder.Entity("API_PRIMECRM.Domain.Models.Masters.PaymentMethod", b =>
                {
                    b.Navigation("RestockOrders");
                });

            modelBuilder.Entity("API_PRIMECRM.Domain.Models.Masters.Product", b =>
                {
                    b.Navigation("InventoryMovements");

                    b.Navigation("RestockOrders");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("API_PRIMECRM.Domain.Models.Masters.SalesChannel", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("API_PRIMECRM.Domain.Models.Ventas.Sale", b =>
                {
                    b.Navigation("LiquidationItem");
                });
#pragma warning restore 612, 618
        }
    }
}
