<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\API_PRIMECRM.Application\API_PRIMECRM.Application.csproj" />
    <ProjectReference Include="..\API_PRIMECRM.Infraestructure\API_PRIMECRM.Infraestructure.csproj" />
    <ProjectReference Include="..\API_PRIMECRM.Domain\API_PRIMECRM.Domain.csproj" />
  </ItemGroup>

</Project>
